AWSTemplateFormatVersion: 2010-09-09
#
#
#
#
# Description: This CF will create two EC2 instances and a Load Balancer
#

Parameters:
  SubnetIDA:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet A to deploy EC2 instance into
  SubnetIDB:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet B to deploy EC2 instance into
  SecurityGroupIDs:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: List of Security Groups to add to EC2 instance
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
  CreationDate:
    Description: Enter today's Date for tagging purposes
    Type: String
    Default: $(date)
  ELBType:
    Description: The type of Elastic LoadBalancer
    Type: String
    Default: application
 

Mappings:
  AWSRegionToAMI:
    us-east-1:
      AMIID: ami-0fbe919e06f97301e
    us-east-2:
      AMIID: ami-0fbe919e06f97301e

Resources:

#First WebAppStackInstance
  EC2InstanceA:
    Type: AWS::EC2::Instance                     
    Properties:
      ImageId:
        !FindInMap                                 # This is an example of the short form YAML FindInMap function
          - AWSRegionToAMI                         # It accepts three parameters each denoted by a hyphen (-)
          - !Ref AWS::Region
          - AMIID
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroupIDs
      SubnetId: !Ref SubnetIDA
     
      Tags:                                      # Tags are an example of a sequence of mappings in YAML,
        -                                        # each key/value pair is separated by a hyphen
          Key: Name
          Value: WebAppStack-ONE      
        -
          Key: Environment
          Value: Development
        -
          Key: CreatedBy
          Value: Brian Keith
        - 
          Key: CreatedDate
          Value: !Ref CreationDate
        - 
          Key: Purpose
          Value: WebAppStack first instance

#Second WebAppStackInstance
  EC2InstanceB:
    Type: AWS::EC2::Instance                     
    Properties:
      ImageId:
        !FindInMap                                 # This is an example of the short form YAML FindInMap function
          - AWSRegionToAMI                         # It accepts three parameters each denoted by a hyphen (-)
          - !Ref AWS::Region
          - AMIID
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroupIDs
      SubnetId: !Ref SubnetIDB
     
      Tags:                                      # Tags are an example of a sequence of mappings in YAML,
        -                                        # each key/value pair is separated by a hyphen
          Key: Name
          Value: WebAppStack-TWO      
        -
          Key: Environment
          Value: Development
        -
          Key: CreatedBy
          Value: Brian Keith
        - 
          Key: CreatedDate
          Value: !Ref CreationDate
        - 
          Key: Purpose
          Value: WebAppStack second instance

# Add an Application Load Balancer
  elbWebAppStack:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Instances: 
        - Ref: EC2InstanceA
        - Ref: EC2InstanceB
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
    HealthCheck:
      Target: HTTP:80/
      HealthyThreshold: '3'
      UnhealthyThreshold: '5'
      Interval: '30'
      Timeout: '5'
      Tags:                                      # Tags are an example of a sequence of mappings in YAML,
        -                                        # each key/value pair is separated by a hyphen
          Key: Name
          Value: elbWebAppStack     
        -
          Key: Environment
          Value: Development
        -
          Key: CreatedBy
          Value: Brian Keith
        - 
          Key: CreatedDate
          Value: !Ref CreationDate
        - 
          Key: Purpose
          Value: WebAppStack Load Balancer


 
    
 